---
# yamllint disable rule:line-length
name: markdownlint

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ env.cache-version }}-${{ runner.os }}-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-cache-

      - name: Install node_modules
        run: yarn install

      - name: Run markdownlint
        run: npx markdownlint '*.md'
